const VERSION='MASTER MARKET COMPASS V4.0';
const CRYPTO=['BTC','ETH','SOL','XRP','AAVE','ONDO','TAO','UNI','HBAR','LINK'];
const KR=['005930.KS','000660.KS','035420.KS','035720.KS','068270.KS','012450.KS','267260.KS','009150.KS','034730.KS','000270.KS','086520.KQ','247540.KQ'];
const US=['NVDA','MSFT','AMZN','GOOGL','META','AVGO','AMD','PLTR','CRWD','TSLA','VRT','IREN','ABCL','CRCL','BAH','SPCX','RKLB','ASTS','COIN','HOOD'];
const META={
 '005930.KS':{theme:'Semiconductor / AI',future:82,structural:82,cat:'AI_INFRA',breaker:'memory/logic cycle deterioration, margin compression, capex inefficiency'},
 '000660.KS':{theme:'HBM / AI Semiconductor',future:88,structural:88,cat:'AI_INFRA',breaker:'HBM demand/capacity pricing deterioration, customer concentration'},
 '035420.KS':{theme:'Digital Platform / AI',future:72,structural:70,cat:'DIGITAL',breaker:'core user monetization decline, platform competition'},
 '035720.KS':{theme:'Digital Platform / AI',future:70,structural:68,cat:'DIGITAL',breaker:'core engagement/monetization deterioration'},
 '068270.KS':{theme:'Biopharma / Biosimilar',future:78,structural:76,cat:'BIOTECH',breaker:'pipeline/regulatory/commercial execution deterioration'},
 '012450.KS':{theme:'Defense / Aerospace',future:88,structural:86,cat:'DEFENSE',breaker:'order/backlog deterioration, export/regulatory shock'},
 '267260.KS':{theme:'Power / Grid',future:84,structural:82,cat:'POWER',breaker:'order cycle/margins/capex deterioration'},
 '009150.KS':{theme:'Semiconductor Equipment',future:80,structural:78,cat:'AI_INFRA',breaker:'semiconductor capex cycle downturn'},
 '034730.KS':{theme:'Energy / Infrastructure',future:74,structural:72,cat:'POWER',breaker:'project economics/debt deterioration'},
 '000270.KS':{theme:'Mobility / EV',future:68,structural:62,cat:'MOBILITY',breaker:'global demand/margin deterioration'},
 '086520.KQ':{theme:'Battery Materials / Energy',future:78,structural:72,cat:'ENERGY',breaker:'battery demand/pricing/capital discipline deterioration'},
 '247540.KQ':{theme:'Battery Materials / Energy',future:80,structural:74,cat:'ENERGY',breaker:'battery cycle/pricing deterioration'},
 NVDA:{theme:'AI Compute',future:96,structural:96,cat:'AI_INFRA',breaker:'AI capex slowdown, accelerator moat erosion, gross-margin deterioration'},
 MSFT:{theme:'Cloud / AI',future:94,structural:93,cat:'AI_INFRA',breaker:'cloud growth/margins deterioration, AI monetization lag'},
 AMZN:{theme:'Cloud / AI / Logistics',future:90,structural:90,cat:'AI_INFRA',breaker:'AWS growth/margin deterioration, retail economics weakening'},
 GOOGL:{theme:'AI / Search / Cloud',future:92,structural:91,cat:'AI_INFRA',breaker:'search economics disruption, cloud/AI monetization deterioration'},
 META:{theme:'AI / Digital Ads',future:89,structural:87,cat:'AI_INFRA',breaker:'ad economics/engagement deterioration, AI capex returns weaken'},
 AVGO:{theme:'AI Semiconductors / Networking',future:94,structural:92,cat:'AI_INFRA',breaker:'AI networking/custom silicon demand deterioration'},
 AMD:{theme:'AI Compute',future:90,structural:88,cat:'AI_INFRA',breaker:'accelerator adoption/competitive position deterioration'},
 PLTR:{theme:'AI Software / Defense',future:94,structural:90,cat:'AI_DEFENSE',breaker:'commercial growth/margins or government demand deterioration'},
 CRWD:{theme:'Cybersecurity / AI',future:91,structural:90,cat:'CYBER',breaker:'ARR retention/margins/customer growth deterioration'},
 TSLA:{theme:'EV / Robotics / Autonomy',future:91,structural:78,cat:'ROBOTICS',breaker:'auto demand/margins, autonomy/robotics execution deterioration'},
 VRT:{theme:'Data Center Power / Cooling',future:95,structural:95,cat:'AI_INFRA',breaker:'data-center capex slowdown, backlog/margins deterioration'},
 IREN:{theme:'AI Data Center / Power',future:97,structural:96,cat:'AI_INFRA',breaker:'AI demand, power access, customer concentration, capex/debt or cloud economics deterioration'},
 ABCL:{theme:'AI / Antibody Drug Discovery',future:94,structural:86,cat:'BIOTECH',breaker:'clinical failure, pipeline attrition, partner/milestone weakness, cash runway compression'},
 CRCL:{theme:'Stablecoin / Digital Finance',future:97,structural:96,cat:'STABLECOIN',breaker:'USDC adoption slowdown, reserve yield compression, regulatory/business-model disruption'},
 BAH:{theme:'Defense / Government AI / Cyber',future:89,structural:88,cat:'AI_DEFENSE',breaker:'government demand/backlog deterioration, contract concentration, margin pressure'},
 SPCX:{theme:'Space / Starlink / AI Infrastructure',future:99,structural:97,cat:'SPACE',breaker:'Starlink growth/profitability deterioration, launch/Starship execution failure, AI capex returns weaken'},
 RKLB:{theme:'Space / Launch / Satellites',future:95,structural:92,cat:'SPACE',breaker:'launch cadence/reliability, Neutron execution, backlog economics deterioration'},
 ASTS:{theme:'Direct-to-Device Satellite',future:96,structural:90,cat:'SPACE',breaker:'satellite deployment, network performance, carrier economics/regulatory execution'},
 COIN:{theme:'Crypto Financial Infrastructure',future:91,structural:86,cat:'STABLECOIN',breaker:'crypto volumes/regulation/custody economics deterioration'},
 HOOD:{theme:'Digital Brokerage / Crypto Finance',future:86,structural:82,cat:'DIGITAL',breaker:'transaction economics, user growth, crypto/regulatory dependence deterioration'}
};
const POS='MMC_POSITIONS_V4',THESIS='MMC_THESIS_V4',LAST='MMC_LAST_SCAN_V4',ALERT='MMC_ALERT_STATE_V4';
const LEGACY_POS='MMC_POSITIONS_V3',LEGACY_THESIS='MMC_THESIS_V3',LEGACY_LAST='MMC_LAST_SCAN_V3';
const cors=()=>({'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-scalper-pin'});
const j=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8',...cors()}});
const auth=(req,e)=>{const p=e.SCALPER_PIN||'';return !!p&&req.headers.get('x-scalper-pin')===p};
const num=(x,d=null)=>{const n=Number(x);return Number.isFinite(n)?n:d};
async function fetchJson(url){const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
async function yahooChart(symbol,range='2y',interval='1d'){const z=await fetchJson(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=${range}&interval=${interval}&events=div%2Csplits`);const q=z.chart?.result?.[0];if(!q)throw Error(`No chart ${symbol}`);const c=q.indicators.quote[0],a=[];for(let i=0;i<(q.timestamp||[]).length;i++){const cl=num(c.close[i]);if(cl!=null)a.push({t:q.timestamp[i]*1000,o:num(c.open[i]),h:num(c.high[i]),l:num(c.low[i]),c:cl,v:num(c.volume[i])})}if(a.length<60)throw Error(`Insufficient chart ${symbol}`);return {meta:q.meta,a}}
async function yahooSummary(symbol){const modules='price,summaryDetail,defaultKeyStatistics,financialData,summaryProfile';for(const host of ['query2','query1']){try{const z=await fetchJson(`https://${host}.finance.yahoo.com/v10/finance/quoteSummary/${encodeURIComponent(symbol)}?modules=${modules}`);const r=z.quoteSummary?.result?.[0];if(r)return r}catch{}}return null}
async function yahooTimeseries(symbol){const p1=Math.floor(Date.now()/1000)-86400*900;const types='quarterlyTotalRevenue,quarterlyNetIncome,quarterlyOperatingCashFlow,quarterlyFreeCashFlow,quarterlyDilutedEPS';try{const z=await fetchJson(`https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/${encodeURIComponent(symbol)}?type=${types}&period1=${p1}&period2=${Math.floor(Date.now()/1000)}&merge=false`);return z.timeseries?.result||[]}catch{return []}}
function raw(m,k){return num(m?.[k]?.raw,m?.[k]?.fmt??null)}
function pick(o,...ks){for(const k of ks){const v=raw(o,k);if(v!=null)return v}return null}
function ret(a,n){return a.length>n?a.at(-1).c/a.at(-1-n).c-1:null}
function sma(a,n){const x=a.slice(-Math.min(n,a.length));return x.length?x.reduce((s,v)=>s+v.c,0)/x.length:null}
function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i].c-a[i-1].c;if(d>0)g+=d;else l-=d}return l===0?100:100-100/(1+g/l)}
function vol(a,n=30){const x=a.slice(-n).map(v=>v.c);if(!x.length)return null;const m=x.reduce((s,v)=>s+v,0)/x.length;return Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/x.length)/(m||1)}
function dd(a,n=252){let peak=0,m=0;for(const x of a.slice(-n)){peak=Math.max(peak,x.c);if(peak)m=Math.max(m,1-x.c/peak)}return m}
function pct(v){return v==null?null:v*100}
function valuation(f){return {pe:pick(f?.defaultKeyStatistics,'trailingPE')??pick(f?.summaryDetail,'trailingPE'),forwardPE:pick(f?.defaultKeyStatistics,'forwardPE')??pick(f?.summaryDetail,'forwardPE'),peg:pick(f?.defaultKeyStatistics,'pegRatio'),ps:pick(f?.defaultKeyStatistics,'priceToSalesTrailing12Months'),pb:pick(f?.defaultKeyStatistics,'priceToBook'),evEbitda:pick(f?.defaultKeyStatistics,'enterpriseToEbitda'),evSales:pick(f?.defaultKeyStatistics,'enterpriseToRevenue'),marketCap:pick(f?.price,'marketCap')}}
function fundamentals(f){const d=f?.financialData||{},k=f?.defaultKeyStatistics||{},sd=f?.summaryDetail||{},p=f?.price||{};return {revenueGrowth:pick(d,'revenueGrowth'),earningsGrowth:pick(d,'earningsGrowth'),grossMargins:pick(d,'grossMargins'),operatingMargins:pick(d,'operatingMargins'),profitMargins:pick(d,'profitMargins'),roe:pick(d,'returnOnEquity'),roa:pick(d,'returnOnAssets'),debtToEquity:pick(d,'debtToEquity'),currentRatio:pick(d,'currentRatio'),freeCashflow:pick(d,'freeCashflow'),operatingCashflow:pick(d,'operatingCashflow'),totalCash:pick(d,'totalCash'),totalDebt:pick(d,'totalDebt'),name:p.shortName||p.longName||null,industry:f?.summaryProfile?.industry||null,sector:f?.summaryProfile?.sector||null}}
function normalizeGrowth(v){return v==null?0:Math.max(-20,Math.min(20,v*100))}
function qualityScore(g){let s=50;s+=normalizeGrowth(g.revenueGrowth)*.6;s+=normalizeGrowth(g.earningsGrowth)*.8;s+=Math.max(-12,Math.min(12,(g.roe??0)*40));if(g.operatingMargins!=null)s+=Math.max(-8,Math.min(8,g.operatingMargins*20));if(g.freeCashflow!=null&&g.freeCashflow>0)s+=5;if(g.debtToEquity!=null){if(g.debtToEquity<80)s+=4;else if(g.debtToEquity>200)s-=7}return Math.round(Math.max(0,Math.min(100,s)))}
function valuationScore(v){let s=50;const pe=v.forwardPE??v.pe;if(pe!=null){if(pe<=18)s+=12;else if(pe<=28)s+=6;else if(pe>55)s-=12;else if(pe>35)s-=6}if(v.peg!=null){if(v.peg<=1.5)s+=10;else if(v.peg>3)s-=10}if(v.evEbitda!=null){if(v.evEbitda<15)s+=6;else if(v.evEbitda>35)s-=7}return Math.max(0,Math.min(100,Math.round(s)))}
function marketScore(x){let s=50;s+=Math.max(-12,Math.min(12,(x.r6??0)*60));s+=Math.max(-10,Math.min(10,(x.ry??0)*25));s+=x.trend200>0?8:-7;s+=x.trend50>0?5:-3;if(x.rsi>=45&&x.rsi<=68)s+=5;if(x.dd>0.45)s-=6;return Math.max(0,Math.min(100,Math.round(s)))}
function growthScore(g){let s=50;s+=Math.max(-20,Math.min(20,(g.revenueGrowth??0)*70));s+=Math.max(-20,Math.min(20,(g.earningsGrowth??0)*50));if((g.freeCashflow??0)>0)s+=5;return Math.max(0,Math.min(100,Math.round(s)))}
function acceleration(series){if(!series?.length)return {label:'DATA LIMITED',score:50};const clean=k=>series.flatMap(r=>(r?.[k]||[]).map(x=>num(x.reportedValue?.raw??x.raw??x.reportedValue)).filter(v=>v!=null)).slice(-8);const slope=a=>a.length<4?null:(a.at(-1)-a.at(-2))-(a.at(-2)-a.at(-3));const out={revenue:slope(clean('quarterlyTotalRevenue')),earnings:slope(clean('quarterlyNetIncome')),cashflow:slope(clean('quarterlyOperatingCashFlow'))};const pos=[out.revenue,out.earnings,out.cashflow].filter(v=>v!=null);const sc=pos.length?pos.filter(v=>v>0).length/pos.length:.5;out.score=Math.round(sc*100);out.label=sc>=.67?'ACCELERATING':sc<=.33?'DECELERATING':'MIXED';return out}
function moatScore(g,v){let s=35;if((g.roe??0)>.20)s+=15;else if((g.roe??0)>.12)s+=8;if((g.operatingMargins??0)>.20)s+=15;else if((g.operatingMargins??0)>.10)s+=7;if((g.grossMargins??0)>.50)s+=8;else if((g.grossMargins??0)>.30)s+=4;if((g.freeCashflow??0)>0)s+=10;if(g.debtToEquity!=null){if(g.debtToEquity<80)s+=8;else if(g.debtToEquity>200)s-=10}if((v.pe??99)<40)s+=4;return Math.max(0,Math.min(100,Math.round(s)))}
function industryBenchmarks(items){const map={};for(const x of items){if(!x.industry||x.type==='COIN')continue;(map[x.industry]??=[]).push(x)}for(const x of items){if(x.type==='COIN'){x.industryBench={peerCount:0};x.industryValueScore=50;continue}const peer=map[x.industry]||[];const med=k=>{const a=peer.map(y=>y.v?.[k]).filter(v=>v!=null).sort((a,b)=>a-b);return a.length?a[Math.floor(a.length/2)]:null};x.industryBench={peerCount:peer.length,peMedian:med('forwardPE')??med('pe'),evEbitdaMedian:med('evEbitda')};let s=50;const pe=x.v?.forwardPE??x.v?.pe,b=x.industryBench;if(pe!=null&&b.peMedian!=null){if(pe<b.peMedian*.8)s+=18;else if(pe<b.peMedian)s+=8;else if(pe>b.peMedian*1.5)s-=15;else if(pe>b.peMedian*1.2)s-=8}if(x.v?.evEbitda!=null&&b.evEbitdaMedian!=null){if(x.v.evEbitda<b.evEbitdaMedian*.8)s+=8;else if(x.v.evEbitda>b.evEbitdaMedian*1.5)s-=8}x.industryValueScore=Math.max(0,Math.min(100,Math.round(s)))}return items}
function thematic(x){const m=META[x.symbol]||{theme:x.industry||'Unknown',future:50,structural:50,cat:'GENERAL',breaker:'fundamental thesis deterioration'};let structural=m.structural,future=m.future;const g=x.f||{};if(x.type!=='COIN'){if(g.revenueGrowth!=null)structural=Math.max(0,Math.min(100,Math.round(structural+Math.max(-8,Math.min(8,g.revenueGrowth*20)))));if(x.accel?.label==='ACCELERATING')structural=Math.min(100,structural+5);if(x.accel?.label==='DECELERATING')structural=Math.max(0,structural-8);if(g.freeCashflow!=null&&g.freeCashflow>0)future=Math.min(100,future+2)}return {theme:m.theme,category:m.cat,structuralScore:structural,futureScore:future,thesisBreaker:m.breaker}}
function thesisHealth(x,t){if(!t)return {status:'NO_THESIS',action:'SET_THESIS',reasons:['매수 당시 투자논리가 저장되어 있지 않습니다.']};const g=x.f||{},r=[];let bad=0,good=0;const chk=(label,actual,limit,op,txt)=>{if(limit==null||actual==null)return;if(op(actual,limit)){good++}else{bad++;r.push(txt)}};chk('revenue',g.revenueGrowth,t.minRevenueGrowth,(a,b)=>a>=b/100,`매출 성장률 ${pct(g.revenueGrowth).toFixed(1)}% < 기준 ${t.minRevenueGrowth}%`);chk('earnings',g.earningsGrowth,t.minEarningsGrowth,(a,b)=>a>=b/100,`이익 성장률 ${pct(g.earningsGrowth).toFixed(1)}% < 기준 ${t.minEarningsGrowth}%`);chk('debt',g.debtToEquity,t.maxDebtToEquity,(a,b)=>a<=b,`D/E ${g.debtToEquity.toFixed(0)} > 기준 ${t.maxDebtToEquity}`);chk('roe',g.roe,t.minROE,(a,b)=>a>=b/100,`ROE ${pct(g.roe).toFixed(1)}% < 기준 ${t.minROE}%`);if(x.accel?.label==='DECELERATING'){bad++;r.push('최근 실적 흐름이 둔화/악화 방향입니다.')}if(x.structuralScore<55){bad++;r.push('구조적 성장 점수가 낮아졌습니다.')}if(bad>=2)return {status:'BROKEN',action:'REVIEW_SELL',reasons:r};if(bad===1)return {status:'REVIEW',action:'REVIEW',reasons:r};return {status:good?'INTACT':'REVIEW',action:good?'HOLD_ADD_REVIEW':'REVIEW',reasons:r.length?r:['저장된 투자논리의 핵심 조건이 현재 데이터상 유지됩니다.']}}
function goodCrash(x){if(x.type==='COIN')return {flag:false,reason:'암호자산은 기업 펀더멘털 급락 모델에서 제외'};const f=x.f||{},stable=(f.revenueGrowth??-1)>-.05&&(f.earningsGrowth??-1)>-.20&&x.accel?.label!=='DECELERATING';const flag=x.dd>=.20&&x.quality>=70&&x.moat>=65&&stable&&x.industryValueScore>=45;return {flag,score:Math.round(x.quality*.3+x.moat*.25+x.structuralScore*.2+x.futureScore*.15+x.industryValueScore*.1),reason:flag?'가격 조정은 크지만 질·구조적 성장·실적 흐름이 상대적으로 유지됩니다.':'조건 일부 미충족'}}
function compassScore(x){if(x.type==='COIN')return Math.round(x.market*.35+x.structuralScore*.25+x.futureScore*.25+x.r6*100*.15);return Math.round(x.quality*.20+x.growth*.10+x.structuralScore*.20+x.futureScore*.20+x.industryValueScore*.10+x.moat*.10+x.market*.10)}
function grade(x){if(x.type==='COIN')return x.compassScore>=75?'DIGITAL-ASSET WATCH':'DIGITAL-ASSET REVIEW';if(x.compassScore>=80)return 'FUTURE CORE / STUDY';if(x.compassScore>=70)return 'STRUCTURAL GROWTH WATCH';if(x.compassScore>=60)return 'REVIEW';return 'PASS / DATA CHECK'}
function lenses(x){return {buffett:Math.round(x.quality*.5+x.moat*.2+x.industryValueScore*.15+x.market*.15),lynch:Math.round(x.growth*.35+x.structuralScore*.3+x.valuation*.15+x.quality*.1+x.market*.1),druckenmiller:Math.round(x.market*.35+x.growth*.25+x.futureScore*.2+x.structuralScore*.2),graham:Math.round(x.industryValueScore*.45+x.quality*.25+x.market*.15+x.moat*.15),padorbubu:Math.round(x.quality*.35+x.structuralScore*.25+x.futureScore*.2+x.market*.1+x.valuation*.1)}}
async function stock(type,symbol,thesis){const c=await yahooChart(symbol),f=await yahooSummary(symbol),ts=await yahooTimeseries(symbol),a=c.a,fs=fundamentals(f),v=valuation(f);const x={type,symbol,name:fs.name||symbol,price:a.at(-1)?.c,a,r1:ret(a,21),r6:ret(a,126),ry:ret(a,252),rsi:rsi(a),dd:dd(a),vol:vol(a),trend50:a.at(-1).c/(sma(a,50)||a.at(-1).c)-1,trend200:a.at(-1).c/(sma(a,200)||a.at(-1).c)-1,f:fs,v,industry:fs.industry||META[symbol]?.theme||'Unknown',sector:fs.sector||META[symbol]?.cat||'Unknown',accel:acceleration(ts)};x.growth=growthScore(fs);x.quality=qualityScore(fs);x.valuation=valuationScore(v);x.moat=moatScore(fs,v);x.market=marketScore(x);Object.assign(x,thematic(x));x.lenses=lenses(x);x.goodCrash=goodCrash(x);x.thesis=thesisHealth(x,thesis);x.compassScore=compassScore(x);x.grade=grade(x);return x}
async function coin(symbol){const z=await fetchJson(`https://api.upbit.com/v1/candles/days?market=KRW-${symbol}&count=300`),a=z.reverse().map(x=>({t:Date.parse(x.candle_date_time_utc+'Z'),c:+x.trade_price}));const x={type:'COIN',symbol,price:a.at(-1)?.c,a,r1:ret(a,21),r6:ret(a,126),ry:ret(a,252),rsi:rsi(a),dd:dd(a),vol:vol(a)};x.trend50=x.price/(sma(a,50)||x.price)-1;x.trend200=x.price/(sma(a,200)||x.price)-1;x.market=marketScore(x);x.growth=Math.max(0,Math.min(100,Math.round(50+(x.r6||0)*60+(x.ry||0)*25)));x.quality=50;x.valuation=50;x.moat=50;Object.assign(x,thematic(x));x.industry='Digital Assets';x.sector='Crypto';x.lenses=lenses(x);x.goodCrash={flag:false,reason:'기업 펀더멘털 대상 아님'};x.thesis={status:'DIGITAL_ASSET',action:'THESIS_REVIEW',reasons:['암호자산은 기업 재무 대신 네트워크/시장구조를 별도 확인합니다.']};x.compassScore=compassScore(x);x.grade=grade(x);return x}
function slim(x){const y={...x};delete y.a;return y}
async function mapLimit(items,limit,fn){const out=new Array(items.length),errs=[];let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;try{out[i]=await fn(items[i])}catch(e){errs.push({type:items[i].type,symbol:items[i].symbol,error:String(e.message||e)})}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return {out,errs}}
async function getKV(e,k,d){if(!e.SCALPER_KV)return d;try{return JSON.parse(await e.SCALPER_KV.get(k)||JSON.stringify(d))}catch{return d}}
async function putKV(e,k,v){if(e.SCALPER_KV)await e.SCALPER_KV.put(k,JSON.stringify(v))}
async function scan(e){const theses=await getKV(e,THESIS,await getKV(e,LEGACY_THESIS,{})),jobs=[...KR.map(symbol=>({type:'KR',symbol})),...US.map(symbol=>({type:'US',symbol})),...CRYPTO.map(symbol=>({type:'COIN',symbol}))];const r=await mapLimit(jobs,8,j=>j.type==='COIN'?coin(j.symbol):stock(j.type,j.symbol,theses[j.symbol]));const out=r.out.filter(Boolean);industryBenchmarks(out);for(const x of out){x.goodCrash=goodCrash(x);x.thesis=thesisHealth(x,theses[x.symbol]);x.lenses=lenses(x);x.compassScore=compassScore(x);x.grade=grade(x)}out.sort((a,b)=>b.compassScore-a.compassScore);const avg=out.length?out.reduce((s,x)=>s+x.market,0)/out.length:50;const discovery=out.filter(x=>x.futureScore>=75&&x.structuralScore>=70).sort((a,b)=>b.compassScore-a.compassScore).slice(0,12);const thematicMap={};for(const x of out){const k=x.category||'GENERAL';(thematicMap[k]??={count:0,avg:0});thematicMap[k].count++;thematicMap[k].avg+=x.compassScore}for(const k of Object.keys(thematicMap))thematicMap[k].avg=Math.round(thematicMap[k].avg/thematicMap[k].count);return {version:VERSION,at:new Date().toISOString(),regime:avg>=65?'RISK-ON':avg<=40?'RISK-OFF':'TRANSITION',universe:{KR:KR.length,US:US.length,CRYPTO:CRYPTO.length,total:jobs.length},method:'Quality + Structural Growth + Future Industry + Industry-relative Value + Market; exploratory decision-support only',candidates:out.slice(0,18).map(slim),discoveryCandidates:discovery.map(slim),goodCrashCandidates:out.filter(x=>x.goodCrash.flag).sort((a,b)=>b.goodCrash.score-a.goodCrash.score).slice(0,10).map(slim),thesisReview:out.filter(x=>x.thesis.status==='REVIEW'||x.thesis.status==='BROKEN').slice(0,15).map(slim),all:out.map(slim),themeSummary:thematicMap,errors:r.errs,thesisCount:Object.keys(theses).length}}
async function sha256(text){const b=new TextEncoder().encode(text),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function tg(e,text){if(!e.TELEGRAM_BOT_TOKEN||!e.TELEGRAM_CHAT_ID)throw Error('Telegram Secret 필요');const r=await fetch(`https://api.telegram.org/bot${e.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:e.TELEGRAM_CHAT_ID,text,parse_mode:'HTML'})});if(!r.ok)throw Error('Telegram 전송 실패')}
function alertDigest(s){const a=[];for(const x of s.all||[]){if(x.type!=='COIN'&&x.thesis?.status==='BROKEN')a.push(`🔴 ${x.name||x.symbol}: THESIS BROKEN → REVIEW\n${(x.thesis.reasons||[]).slice(0,2).join(' / ')}`);if(x.type!=='COIN'&&x.goodCrash?.flag)a.push(`💎 ${x.name||x.symbol}: 좋은 기업 급락 후보\nDD ${pct(x.dd).toFixed(1)}% · 구조적 ${x.structuralScore} · 미래 ${x.futureScore}`);if(x.futureScore>=95&&x.structuralScore>=90)a.push(`🚀 ${x.name||x.symbol}: 미래산업 구조적 성장 WATCH\n${x.theme} · Compass ${x.compassScore}`)}return a.join('\n\n').slice(0,3500)}
export default {async fetch(req,e){if(req.method==='OPTIONS')return new Response('',{headers:cors()});if(!auth(req,e))return j({ok:false,error:'PIN required'},401);const p=new URL(req.url).pathname;try{if(p==='/health')return j({ok:true,version:VERSION,kv:!!e.SCALPER_KV,telegramConfigured:!!(e.TELEGRAM_BOT_TOKEN&&e.TELEGRAM_CHAT_ID),pinConfigured:!!e.SCALPER_PIN,time:new Date().toISOString(),cron:'0 * * * *',keys:{positions:POS,thesis:THESIS,last:LAST},universe:{KR:KR.length,US:US.length,CRYPTO:CRYPTO.length}});if(p==='/test-telegram'){await tg(e,`🧪 ${VERSION}\nTelegram 연결 성공`);return j({ok:true})}if(p==='/scan'){const s=await scan(e);await putKV(e,LAST,s);return j(s)}if(p==='/last')return j(await getKV(e,LAST,await getKV(e,LEGACY_LAST,{error:'no scan'})));if(p==='/positions'&&req.method==='GET')return j({positions:await getKV(e,POS,await getKV(e,LEGACY_POS,{}))});if(p==='/positions'&&req.method==='POST'){const b=await req.json(),v=await getKV(e,POS,{});v[b.symbol]={...(v[b.symbol]||{}),...b,updatedAt:Date.now()};await putKV(e,POS,v);return j({positions:v})}if(p==='/thesis'&&req.method==='GET')return j(await getKV(e,THESIS,{}));if(p==='/thesis'&&req.method==='POST'){const b=await req.json(),v=await getKV(e,THESIS,{});v[b.symbol]={...(v[b.symbol]||{}),...b,updatedAt:Date.now()};await putKV(e,THESIS,v);return j(v)}return j({ok:false,error:'Not found'},404)}catch(err){return j({ok:false,error:String(err.stack||err)},500)}},async scheduled(event,e,ctx){ctx.waitUntil((async()=>{try{const s=await scan(e);await putKV(e,LAST,s);if(e.TELEGRAM_BOT_TOKEN&&e.TELEGRAM_CHAT_ID){const digest=alertDigest(s),hash=digest?await sha256(digest):'',prior=await getKV(e,ALERT,{});if(digest&&hash!==prior.hash){await tg(e,`🧭 <b>${VERSION}</b>\n${digest}\n\n※ 주문 없음 · 투자논리와 펀더멘털을 먼저 확인하세요.`);await putKV(e,ALERT,{hash,at:Date.now()})}}}catch(err){if(e.TELEGRAM_BOT_TOKEN&&e.TELEGRAM_CHAT_ID)try{await tg(e,`⚠️ ${VERSION}\n스캔 오류: ${String(err.message||err)}`)}catch{}}})())}};
