const VERSION='MASTER MARKET COMPASS V3.0';
const COINS=['BTC','ETH','SOL','XRP','AAVE','ONDO','TAO','UNI','HBAR','LINK'];
const KR=['005930.KS','000660.KS','035420.KS','035720.KS','068270.KS','012450.KS','267260.KS','009150.KS','034730.KS','000270.KS'];
const US=['NVDA','MSFT','AMZN','GOOGL','META','AVGO','AMD','PLTR','CRWD','TSLA','VRT','IREN'];
const POS='MMC_POSITIONS_V3', THESIS='MMC_THESIS_V3', LAST='MMC_LAST_SCAN_V3';
const cors=()=>({'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-scalper-pin'});
const j=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8',...cors()}});
const auth=(req,e)=>{const p=e.SCALPER_PIN||'';return !!p&&req.headers.get('x-scalper-pin')===p;};
const num=(x,d=null)=>{const n=Number(x);return Number.isFinite(n)?n:d};
async function fetchJson(url){const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json'} });if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
async function yahooChart(symbol,range='2y',interval='1d'){const z=await fetchJson(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=${range}&interval=${interval}&events=div%2Csplits`);const q=z.chart?.result?.[0];if(!q)throw Error(`No chart ${symbol}`);const c=q.indicators.quote[0],a=[];for(let i=0;i<q.timestamp.length;i++){const cl=num(c.close[i]);if(cl!=null)a.push({t:q.timestamp[i]*1000,o:num(c.open[i]),h:num(c.high[i]),l:num(c.low[i]),c:cl,v:num(c.volume[i])})}return {meta:q.meta,a}}
async function yahooSummary(symbol){const modules='price,summaryDetail,defaultKeyStatistics,financialData,summaryProfile';for(const host of ['query2','query1']){try{const z=await fetchJson(`https://${host}.finance.yahoo.com/v10/finance/quoteSummary/${encodeURIComponent(symbol)}?modules=${modules}`);const r=z.quoteSummary?.result?.[0];if(r)return r}catch{}}throw Error(`Fundamentals unavailable: ${symbol}`)}
async function yahooTimeseries(symbol){const p1=Math.floor(Date.now()/1000)-86400*900;const types='quarterlyTotalRevenue,quarterlyNetIncome,quarterlyOperatingCashFlow,quarterlyFreeCashFlow,quarterlyDilutedEPS';try{const z=await fetchJson(`https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/${encodeURIComponent(symbol)}?type=${types}&period1=${p1}&period2=${Math.floor(Date.now()/1000)}&merge=false`);return z.timeseries?.result||[]}catch{return []}}
function raw(m,k){return num(m?.[k]?.raw,m?.[k]?.fmt??null)}
function pick(o,...ks){for(const k of ks){const v=raw(o,k);if(v!=null)return v}return null}
function ret(a,n){if(a.length<=n)return null;return a.at(-1).c/a.at(-1-n).c-1}
function sma(a,n){const x=a.slice(-Math.min(n,a.length));return x.length?x.reduce((s,v)=>s+v.c,0)/x.length:null}
function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i].c-a[i-1].c;if(d>0)g+=d;else l-=d}return l===0?100:100-100/(1+g/l)}
function vol(a,n=30){const x=a.slice(-n).map(v=>v.c);if(!x.length)return null;const m=x.reduce((s,v)=>s+v,0)/x.length;return Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/x.length)/(m||1)}
function dd(a,n=252){let peak=0,m=0;for(const x of a.slice(-n)){peak=Math.max(peak,x.c);if(peak)m=Math.max(m,1-x.c/peak)}return m}
function pct(v){return v==null?null:v*100}
function valuation(f){return {pe:pick(f.defaultKeyStatistics,'trailingPE')??pick(f.summaryDetail,'trailingPE'),forwardPE:pick(f.defaultKeyStatistics,'forwardPE')??pick(f.summaryDetail,'forwardPE'),peg:pick(f.defaultKeyStatistics,'pegRatio'),ps:pick(f.defaultKeyStatistics,'priceToSalesTrailing12Months'),pb:pick(f.defaultKeyStatistics,'priceToBook'),evEbitda:pick(f.defaultKeyStatistics,'enterpriseToEbitda'),evSales:pick(f.defaultKeyStatistics,'enterpriseToRevenue'),marketCap:pick(f.price,'marketCap')}}
function fundamentals(f){const d=f.financialData||{},k=f.defaultKeyStatistics||{},sd=f.summaryDetail||{},p=f.price||{};return {revenueGrowth:pick(d,'revenueGrowth'),earningsGrowth:pick(d,'earningsGrowth'),grossMargins:pick(d,'grossMargins'),operatingMargins:pick(d,'operatingMargins'),profitMargins:pick(d,'profitMargins'),roe:pick(d,'returnOnEquity'),roa:pick(d,'returnOnAssets'),debtToEquity:pick(d,'debtToEquity'),currentRatio:pick(d,'currentRatio'),freeCashflow:pick(d,'freeCashflow'),operatingCashflow:pick(d,'operatingCashflow'),totalCash:pick(d,'totalCash'),totalDebt:pick(d,'totalDebt'),targetMean:pick(d,'targetMeanPrice'),recommendationKey:d?.recommendationKey||null,earningsQuarterlyGrowth:pick(k,'earningsQuarterlyGrowth'),dividendYield:pick(sd,'dividendYield'),industry:f.summaryProfile?.industry||'Unknown',sector:f.summaryProfile?.sector||'Unknown',name:p.shortName||p.longName||null}}
function normalizeGrowth(v){return v==null?0:Math.max(-20,Math.min(20,v*100))}
function qualityScore(g){let s=50;s+=normalizeGrowth(g.revenueGrowth)*0.6;s+=normalizeGrowth(g.earningsGrowth)*0.8;s+=Math.max(-12,Math.min(12,(g.roe??0)*40));if(g.operatingMargins!=null)s+=Math.max(-8,Math.min(8,g.operatingMargins*20));if(g.freeCashflow!=null&&g.freeCashflow>0)s+=5;if(g.debtToEquity!=null){if(g.debtToEquity<80)s+=4;else if(g.debtToEquity>200)s-=7}return Math.round(Math.max(0,Math.min(100,s)))}
function valuationScore(v){let s=50;const pe=v.forwardPE??v.pe;if(pe!=null){if(pe<=18)s+=12;else if(pe<=28)s+=6;else if(pe>55)s-=12;else if(pe>35)s-=6}if(v.peg!=null){if(v.peg<=1.5)s+=10;else if(v.peg>3)s-=10}if(v.evEbitda!=null){if(v.evEbitda<15)s+=6;else if(v.evEbitda>35)s-=7}return Math.max(0,Math.min(100,Math.round(s)))}
function marketScore(x){let s=50;s+=Math.max(-12,Math.min(12,(x.r6??0)*60));s+=Math.max(-10,Math.min(10,(x.ry??0)*25));s+=x.trend200>0?8:-7;s+=x.trend50>0?5:-3;if(x.rsi>=45&&x.rsi<=68)s+=5;if(x.dd>0.45)s-=6;return Math.max(0,Math.min(100,Math.round(s)))}
function lensScores(x){return {buffett:Math.round(x.quality*.55+x.valuation*.25+x.market*.2),lynch:Math.round(x.quality*.45+x.growth*.3+x.valuation*.15+x.market*.1),druckenmiller:Math.round(x.market*.55+x.growth*.25+x.quality*.1+x.valuation*.1),graham:Math.round(x.valuation*.6+x.quality*.25+x.market*.15),padorbubu:Math.round(x.quality*.5+x.growth*.25+x.market*.15+x.valuation*.1)}}
function acceleration(series){if(!series?.length)return {revenue:null,earnings:null,cashflow:null,label:'DATA LIMITED'};const clean=k=>series.flatMap(r=>{const arr=r?.[k]||[];return arr.map(x=>num(x.reportedValue?.raw??x.raw??x.reportedValue)).filter(v=>v!=null)}).slice(-8);const slope=a=>a.length<4?null:(a.at(-1)-a.at(-2))-(a.at(-2)-a.at(-3));const rg=clean('quarterlyTotalRevenue'),ni=clean('quarterlyNetIncome'),cf=clean('quarterlyOperatingCashFlow');const out={revenue:slope(rg),earnings:slope(ni),cashflow:slope(cf)};const pos=[out.revenue,out.earnings,out.cashflow].filter(v=>v!=null);const score=pos.length?pos.filter(v=>v>0).length/pos.length:0.5;out.score=Math.round(score*100);out.label=score>=.67?'ACCELERATING':score<=.33?'DECELERATING':'MIXED';return out}
function moatScore(g,v){let s=35;if((g.roe??0)>.20)s+=15;else if((g.roe??0)>.12)s+=8;if((g.operatingMargins??0)>.20)s+=15;else if((g.operatingMargins??0)>.10)s+=7;if((g.grossMargins??0)>.50)s+=8;else if((g.grossMargins??0)>.30)s+=4;if((g.freeCashflow??0)>0)s+=10;if(g.debtToEquity!=null){if(g.debtToEquity<80)s+=8;else if(g.debtToEquity>200)s-=10}if((v.pe??99)<40)s+=4;return Math.max(0,Math.min(100,Math.round(s)))}
function industryBenchmarks(items){const map={};for(const x of items){if(!x.industry||x.type==='COIN')continue;(map[x.industry]??=[]).push(x)}for(const x of items){const peer=map[x.industry]||[];const med=k=>{const a=peer.map(y=>y.v?.[k]).filter(v=>v!=null).sort((a,b)=>a-b);return a.length?a[Math.floor(a.length/2)]:null};x.industryBench={peerCount:peer.length,peMedian:med('forwardPE')??med('pe'),psMedian:med('ps'),evEbitdaMedian:med('evEbitda')};let s=50;const b=x.industryBench;const pe=x.v?.forwardPE??x.v?.pe;if(pe!=null&&b.peMedian!=null){if(pe<b.peMedian*.8)s+=18;else if(pe<b.peMedian)s+=8;else if(pe>b.peMedian*1.5)s-=15;else if(pe>b.peMedian*1.2)s-=8}if(x.v?.evEbitda!=null&&b.evEbitdaMedian!=null){if(x.v.evEbitda<b.evEbitdaMedian*.8)s+=8;else if(x.v.evEbitda>b.evEbitdaMedian*1.5)s-=8}x.industryValueScore=Math.max(0,Math.min(100,Math.round(s)));}return items}
function goodCrash(x){if(x.type==='COIN')return {flag:false,reason:'기업 펀더멘털 대상 아님'};const f=x.f||{},a=x.accel||{};const quality=x.quality??0,moat=x.moat??0,drop=x.dd??0;const fundamentalStable=(f.revenueGrowth??-1)>-.05&&(f.earningsGrowth??-1)>-.20&&(a.label!=='DECELERATING');const valuationOK=(x.industryValueScore??x.valuation??0)>=45;const flag=drop>=.20&&quality>=70&&moat>=65&&fundamentalStable&&valuationOK;return {flag,score:Math.round(quality*.3+moat*.3+(x.industryValueScore??x.valuation)*.2+(a.score??50)*.2),reason:flag?'가격 조정은 크지만 질·해자·실적 흐름이 상대적으로 유지됩니다.':'조건 일부 미충족'} }
function investmentGrade(x){if(x.type==='COIN')return x.market>=70?'DIGITAL-ASSET WATCH':'DIGITAL-ASSET REVIEW';const total=Math.round(x.quality*.25+x.growth*.15+x.valuation*.15+x.industryValueScore*.15+x.moat*.15+x.market*.15);if(total>=78)return 'CORE CANDIDATE';if(total>=68)return 'WATCH / STUDY';if(total>=58)return 'REVIEW';return 'PASS'}
function verifyThesis(x,t){if(!t)return {status:'NO_THESIS',action:'SET_THESIS',reasons:['매수 당시 투자논리가 저장되어 있지 않습니다.']};const g=x.f||{},r=[];let bad=0,good=0;if(t.minRevenueGrowth!=null&&g.revenueGrowth!=null){if(g.revenueGrowth>=Number(t.minRevenueGrowth)/100)good++;else{bad++;r.push(`매출 성장률 ${pct(g.revenueGrowth).toFixed(1)}% < 기준 ${Number(t.minRevenueGrowth).toFixed(1)}%`)}}if(t.minEarningsGrowth!=null&&g.earningsGrowth!=null){if(g.earningsGrowth>=Number(t.minEarningsGrowth)/100)good++;else{bad++;r.push(`이익 성장률 ${pct(g.earningsGrowth).toFixed(1)}% < 기준 ${Number(t.minEarningsGrowth).toFixed(1)}%`)}}if(t.maxDebtToEquity!=null&&g.debtToEquity!=null){if(g.debtToEquity<=Number(t.maxDebtToEquity))good++;else{bad++;r.push(`D/E ${g.debtToEquity.toFixed(0)} > 기준 ${Number(t.maxDebtToEquity).toFixed(0)}`)}}if(t.minROE!=null&&g.roe!=null){if(g.roe>=Number(t.minROE)/100)good++;else{bad++;r.push(`ROE ${pct(g.roe).toFixed(1)}% < 기준 ${Number(t.minROE).toFixed(1)}%`)}}if(x.accel?.label==='DECELERATING'){bad++;r.push('최근 실적 흐름이 둔화/악화 방향입니다.')}if(x.goodCrash?.flag)r.push('좋은 기업 급락 후보: 가격 조정과 펀더멘털 변화를 분리해서 검토하세요.');if(bad>=2)return {status:'BROKEN',action:'REVIEW_SELL',reasons:r};if(bad===1)return {status:'REVIEW',action:'REVIEW',reasons:r};return {status:good?'INTACT':'REVIEW',action:good?'HOLD_ADD_REVIEW':'REVIEW',reasons:r.length?r:['저장된 투자논리의 핵심 조건이 현재 데이터상 유지됩니다.']}}
async function stock(type,symbol,thesis){const c=await yahooChart(symbol),f=await yahooSummary(symbol),ts=await yahooTimeseries(symbol),a=c.a,fs=fundamentals(f),v=valuation(f);const x={type,symbol,name:fs.name||symbol,price:a.at(-1)?.c,a,r1:ret(a,21),r6:ret(a,126),ry:ret(a,252),rsi:rsi(a),dd:dd(a),vol:vol(a),trend50:a.at(-1).c/sma(a,50)-1,trend200:a.at(-1).c/sma(a,200)-1,f:fs,v,industry:fs.industry,sector:fs.sector,accel:acceleration(ts)};x.growth=Math.max(0,Math.min(100,Math.round(50+normalizeGrowth(fs.revenueGrowth)*1.2+normalizeGrowth(fs.earningsGrowth)*1.3)));x.quality=qualityScore(fs);x.valuation=valuationScore(v);x.moat=moatScore(fs,v);x.market=marketScore(x);x.lenses=lensScores(x);return x}
async function coin(symbol){const market=`KRW-${symbol}`;const z=await fetchJson(`https://api.upbit.com/v1/candles/days?market=${market}&count=300`);const a=z.reverse().map(x=>({t:Date.parse(x.candle_date_time_utc+'Z'),c:+x.trade_price}));const x={type:'COIN',symbol,price:a.at(-1).c,a,r1:ret(a,21),r6:ret(a,126),ry:ret(a,252),rsi:rsi(a),dd:dd(a),vol:vol(a)};x.trend50=x.price/sma(a,50)-1;x.trend200=x.price/sma(a,200)-1;x.market=marketScore(x);x.growth=Math.round(Math.max(0,Math.min(100,50+(x.r6||0)*60+(x.ry||0)*25)));x.quality=null;x.valuation=null;x.moat=null;x.industry='Digital Assets';x.sector='Crypto';x.industryValueScore=null;x.accel={label:'N/A'};x.grade=investmentGrade(x);x.lenses={buffett:null,lynch:null,druckenmiller:x.market,graham:null,padorbubu:null};return x}
function slim(x){const y={...x};delete y.a;return y}
async function getKV(e,k,d){if(!e.SCALPER_KV)return d;try{return JSON.parse(await e.SCALPER_KV.get(k)||JSON.stringify(d))}catch{return d}}
async function putKV(e,k,v){if(e.SCALPER_KV)await e.SCALPER_KV.put(k,JSON.stringify(v))}
async function scan(e){const theses=await getKV(e,THESIS,{}),out=[],errors=[];const jobs=[...KR.map(symbol=>({type:'KR',symbol,run:()=>stock('KR',symbol,theses[symbol])})),...US.map(symbol=>({type:'US',symbol,run:()=>stock('US',symbol,theses[symbol])})),...COINS.map(symbol=>({type:'COIN',symbol,run:()=>coin(symbol)}))];const settled=await Promise.allSettled(jobs.map(x=>x.run()));settled.forEach((r,i)=>{const job=jobs[i];if(r.status==='fulfilled')out.push(r.value);else errors.push({type:job.type,symbol:job.symbol,error:String(r.reason?.message||r.reason)})});industryBenchmarks(out);for(const x of out){x.goodCrash=goodCrash(x);x.grade=investmentGrade(x);x.thesis=verifyThesis(x,theses[x.symbol]);}const score=x=>x.type==='COIN'?x.market:(x.quality*.25+x.growth*.15+x.valuation*.15+x.industryValueScore*.15+x.moat*.15+x.market*.15);const ranked=out.sort((a,b)=>score(b)-score(a));const avg=ranked.map(x=>x.market).reduce((a,b)=>a+b,0)/(ranked.length||1);return {version:VERSION,at:new Date().toISOString(),regime:avg>=65?'RISK-ON':avg<=40?'RISK-OFF':'TRANSITION',method:'Quality 25% + Growth 15% + Base Valuation 15% + Industry-relative Valuation 15% + Economic Moat 15% + Market 15%; crypto uses market proxy',candidates:ranked.slice(0,15).map(slim),goodCrashCandidates:ranked.filter(x=>x.goodCrash?.flag).sort((a,b)=>b.goodCrash.score-a.goodCrash.score).slice(0,10).map(slim),all:ranked.map(slim),errors,thesisCount:Object.keys(theses).length}}
async function sha256(text){const b=new TextEncoder().encode(text);const h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function tg(e,text){if(!e.TELEGRAM_BOT_TOKEN||!e.TELEGRAM_CHAT_ID)throw Error('Telegram Secret 필요');const r=await fetch(`https://api.telegram.org/bot${e.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:e.TELEGRAM_CHAT_ID,text,parse_mode:'HTML'})});if(!r.ok)throw Error('Telegram 전송 실패')}
function msg(s){return `🧭 <b>${VERSION}</b>\n시장국면: <b>${s.regime}</b>\n\n상위 후보\n${s.candidates.slice(0,7).map((x,i)=>`${i+1}. <b>${x.name||x.symbol}</b> | ${x.grade} | Q${x.quality??'-'} M${x.moat??'-'} IV${x.industryValueScore??'-'} G${x.growth??'-'}`).join('\n')}\n\n좋은 기업 급락 후보 ${s.goodCrashCandidates?.length||0}개\n※ 주문 없음. 가격 하락만으로 매도하지 않고 투자논리 변화 여부를 먼저 검증합니다.`}
export default {async fetch(req,e){if(req.method==='OPTIONS')return new Response('',{headers:cors()});const p=new URL(req.url).pathname;if(!auth(req,e))return j({ok:false,error:'PIN required'},401);try{if(p==='/health')return j({ok:true,version:VERSION,kv:!!e.SCALPER_KV,telegramConfigured:!!(e.TELEGRAM_BOT_TOKEN&&e.TELEGRAM_CHAT_ID),pinConfigured:!!e.SCALPER_PIN,time:new Date().toISOString(),cron:'0 * * * *',keys:{positions:POS,thesis:THESIS,last:LAST}});if(p==='/test-telegram'){await tg(e,`🧪 ${VERSION}\nTelegram 연결 성공`);return j({ok:true})}if(p==='/scan'){const s=await scan(e);await putKV(e,LAST,s);return j(s)}if(p==='/last')return j(await getKV(e,LAST,{error:'no scan'}));if(p==='/positions'&&req.method==='GET')return j(await getKV(e,POS,{}));if(p==='/positions'&&req.method==='POST'){const b=await req.json(),v=await getKV(e,POS,{});v[b.symbol]={...(v[b.symbol]||{}),...b,updatedAt:Date.now()};await putKV(e,POS,v);return j(v)}if(p==='/thesis'&&req.method==='GET')return j(await getKV(e,THESIS,{}));if(p==='/thesis'&&req.method==='POST'){const b=await req.json(),v=await getKV(e,THESIS,{});v[b.symbol]={...(v[b.symbol]||{}),...b,updatedAt:Date.now()};await putKV(e,THESIS,v);return j(v)}return j({ok:false,error:'Not found'},404)}catch(err){return j({ok:false,error:String(err.stack||err)},500)}},async scheduled(event,e,ctx){ctx.waitUntil((async()=>{try{const s=await scan(e);await putKV(e,LAST,s);if(e.TELEGRAM_BOT_TOKEN&&e.TELEGRAM_CHAT_ID){const alerts=[];for(const x of s.all||[]){if(x.type!=='COIN'&&x.thesis?.status==='BROKEN')alerts.push(`🔴 ${x.name||x.symbol}: 투자논리 BROKEN → REVIEW_SELL\n${(x.thesis.reasons||[]).slice(0,2).join(' / ')}`);if(x.type!=='COIN'&&x.goodCrash?.flag)alerts.push(`💎 ${x.name||x.symbol}: 좋은 기업 급락 후보\nDD ${pct(x.dd).toFixed(1)}% · Q${x.quality} · Moat${x.moat}`)}const prior=await getKV(e,'MMC_ALERT_STATE_V3',{});const digest=alerts.join('\n\n').slice(0,3500);const hash=digest?await sha256(digest):'';if(digest&&hash!==prior.hash){await tg(e,`🧭 <b>${VERSION}</b>\n${digest}\n\n※ 주문 없음 · 투자논리와 펀더멘털을 먼저 확인하세요.`);await putKV(e,'MMC_ALERT_STATE_V3',{hash,at:Date.now()})}}}catch(err){if(e.TELEGRAM_BOT_TOKEN&&e.TELEGRAM_CHAT_ID)try{await tg(e,`⚠️ ${VERSION}\n스캔 오류: ${String(err.message||err)}`)}catch{}}})())}};
